### ISSUE TITLE
Bug - error message during startup

### ISSUE THREAD

**Issue by erkr** [EPMatt/awesome-ha-blueprints#485]
### Blueprint name

on_off_schedule_state_persistence

### Home Assistant Core Version

2023.1.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi.
I’ma happy user of the blueprint on_off_schedule_state_persistence.
This bug is not nee, but I now decided to report it. During a start of HA, the automations based on this blueprint tends to intermittently generate errors like this one during startup:
``` 
Logger: homeassistant.components.automation.on_off_schedule_beestenboel
Source: components/zha/switch.py:148 
Integration: Automation (documentation, issues) 
First occurred: 11:10:17 (3 occurrences) 
Last logged: 11:10:17

On-Off schedule Beestenboel: Choose at step 1: choice 1: Error executing script. Unexpected error for call_service at pos 1:
On-Off schedule Beestenboel: Error executing script. Unexpected error for choose at pos 1:
While executing automation automation.on_off_schedule_beestenboel
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 124, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zha/switch.py", line 148, in async_turn_on
    result = await self._on_off_channel.on()
  File "/usr/local/lib/python3.10/site-packages/zigpy/zcl/__init__.py", line 324, in request
    return await self._endpoint.request(
  File "/usr/local/lib/python3.10/site-packages/zigpy/group.py", line 57, in request
    await self.application.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_deconz/zigbee/application.py", line 402, in send_packet
    await self._api.aps_data_request(
  File "/usr/local/lib/python3.10/site-packages/zigpy_deconz/api.py", line 547, in aps_data_request
    return await self._command(
  File "/usr/local/lib/python3.10/site-packages/zigpy_deconz/api.py", line 306, in _command
    return await asyncio.wait_for(fut, timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
``` 

### Automation YAML config

```yaml
alias: On-Off schedule Beestenboel
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - switch.beestenboel_zha_group_0x0002
      on_time: 08:50:00
      off_time: '22:00:00'
      trigger_at_homeassistant_startup: true
```

### To Reproduce

1 create an automation using the blueprint
2 Restart HA
3 Intermittently there is an error

### Expected behavior

No errors 🤓

### Actual Behaviour

Intermittently there are errors during startup

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

I think adding a small delay when the trigger is a restart will solve it. The error is probably caused by zigbee lights that are not yet available.

**Comment by erkr** [comment]
Update: I tested the blueprint with this extra delay action. It seems to fix the issue!
